ADVOCATES = [
    {"id":"sample-priya-menon","name":"Adv. Priya Menon","title":"Debt Recovery Advocate","jurisdictions":["IN"],"specialties":["debt_collection","consumer_notice"],"tier":"free_consult","tier_label":"Free first call","years_experience":8,"rating":4.7,"languages":["English","Hindi","Malayalam"],"bio":"Sample profile for this demo. Focuses on explaining debt recovery notices in plain language.","response_time_hours":12},
    {"id":"sample-arjun-desai","name":"Adv. Arjun Desai","title":"Consumer Notice Advocate","jurisdictions":["IN"],"specialties":["consumer_notice","employment_termination"],"tier":"budget","tier_label":"Rs.1,500-3,000/session","years_experience":6,"rating":4.5,"languages":["English","Hindi","Gujarati"],"bio":"Sample profile for this demo. Helps users organise documents before a consumer complaint.","response_time_hours":24},
    {"id":"sample-meera-iyer","name":"Adv. Meera Iyer","title":"Housing Notice Advocate","jurisdictions":["IN"],"specialties":["eviction_notice","consumer_notice"],"tier":"standard","tier_label":"Rs.3,500-5,000/session","years_experience":11,"rating":4.8,"languages":["English","Tamil"],"bio":"Sample profile for this demo. Works through housing and tenancy notice questions.","response_time_hours":18},
    {"id":"sample-owen-clarke","name":"Owen Clarke","title":"Notice Response Adviser","jurisdictions":["GB"],"specialties":["court_summons","employment_termination"],"tier":"standard","tier_label":"GBP 80-140/session","years_experience":9,"rating":4.6,"languages":["English"],"bio":"Sample profile for this demo. Supports first-pass review of UK notice documents.","response_time_hours":24},
    {"id":"sample-riley-park","name":"Riley Park","title":"Consumer Notice Attorney","jurisdictions":["US"],"specialties":["debt_collection","consumer_notice"],"tier":"premium","tier_label":"$180+/session","years_experience":13,"rating":4.9,"languages":["English","Spanish"],"bio":"Sample profile for this demo. Helps identify questions to raise after a consumer notice.","response_time_hours":36},
    {"id":"sample-jordan-lee","name":"Jordan Lee","title":"Employment Notice Adviser","jurisdictions":["AU","CA","NG"],"specialties":["employment_termination","court_summons"],"tier":"budget","tier_label":"$70-120/session","years_experience":7,"rating":4.4,"languages":["English"],"bio":"Sample profile for this demo. Reviews employment and court notice preparation steps.","response_time_hours":24},
]

def find_advocates(jurisdiction=None, specialty=None, tier=None):
    return [a for a in ADVOCATES if (not jurisdiction or jurisdiction in a["jurisdictions"]) and (not specialty or specialty in a["specialties"]) and (not tier or tier == a["tier"])]
